### ISSUE TITLE
SVM

### ISSUE THREAD

**Issue by vittoriom** [vlall/Swift-Brain#11]
Hi, I saw in the README that SVM are supported, but the svm.swift file is empty. Can you tell me where should I look? Thanks

**Comment by KevinCoble** [comment]
I have a Swift port of LIBSVM I put out in another GitHub repository - KevinCoble/swift-libsvm.  I have XCTest files in the project showing the usage pattern.  It is part of a similar library I have been working on (AI - Neural Nets, SVM, graph tree search, minimax, etc.), but being a port of public-domain code, I felt I should also make that part public.  It doesn't support a few of the options of the full LIBSVM package, but it does add the use of the Accelerate library to speed up the math.

**Comment by istx25** [comment]
Thanks for sharing this, @KevinCoble. Looks really cool. :dancer:
